<a href="https://colab.research.google.com/github/vishweshpattanaik/carisurg-portfolio/blob/main/Week0_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1 - Data Exploration and Cleaning
**Name:** Vishwesh Pattanaik
  
**Programme:** MedTech Pathways 2026

Step 1: Google Drive Setup to mount dataset

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Step 2: Import Libraries and File

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
df_raw = pd.read_csv('/content/drive/My Drive/Carisurg/Week0/EmergencyTriageDataset_Reduced_Dirty.csv')

Step 3: Load the Dataset

In [23]:
print("Number of rows:", df_raw.shape[0])
print("Number of columns:", df_raw.shape[1])

Number of rows: 2205
Number of columns: 11

Step 4: Check the Shape of the Dataset

In [24]:
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

Step 5: Preview the First 10 Rows

In [25]:
print(df_raw.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

Step 6: Check Data Types

In [26]:
print(df_raw['Gender'].unique())

['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

Step 7: Check Unique Values in Gender Column

In [27]:
print(df_raw['Gender'].value_counts())

Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

Step 8: Map Gender Column to Integers

In [28]:
gender_map = {
    'Male'  : 1,
    'MALE'  : 1,
    '1'     : 1,
    'Female': 0,
    'FEMALE': 0,
    '0'     : 0
}

df_raw['gender_clean'] = df_raw['Gender'].map(gender_map)

Step 9: Check for Unmapped Values

In [29]:
print("Unmapped values:", df_raw['gender_clean'].isna().sum())

Unmapped values: 0

Step 10: Drop Old Column and Rename Clean Column

In [30]:
df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'gender_clean': 'Gender'})

Step 11: Verify the Cleaned Column

In [31]:
print("Unique values:", df_raw['Gender'].unique())
print("Data type:", df_raw['Gender'].dtype)
df_raw.head(10)

Unique values: [0 1]
Data type: int64

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0       0
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0       1
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0       0
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0       0
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0       0
5   6   42  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0       1
6   7   75  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0       0
7   8   25  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0       1
8   9   67  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0       0
9  11   82  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0       0